name: Spell checking
on: [pull_request, push]

jobs:
  build:
    name: Spell checking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
      with:
        fetch-depth: 3
    - uses: actions/checkout@v2.0.0
      with:
        path: .git/spell-check
        ref: spelling-data-local
    - uses: check-spelling/check-spelling@0.0.2-alpha
      env:
        bucket: .git
        project: spell-check
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
