name: Spell checking
on: [pull_request_target, push]

jobs:
  build:
    name: Spell checking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - uses: check-spelling/check-spelling@prerelease
      env:
        VERBOSE: 1
