name: Spell checking
on: [pull_request, push]

jobs:
  build:
    name: Spell checking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
      with:
        fetch-depth: 0
    - uses: check-spelling/check-spelling@prerelease
      env:
        bucket: .github/actions
        project: spell-check
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
