name: Spell checking

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  build:
    name: Spell checking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
      with:
        fetch-depth: 2
    - uses: jsoref/check-spelling@prerelease
      env:
        bucket: .github/actions
        project: spelling-data
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
